### PR TITLE
Call NotificationError when toast notification fails on Windows

### PR DESCRIPTION
**Pull request by miniak**

### CODE REVIEW

**Comment by felixrieseberg** [comment]
This looks great :+1:, but it has minor merge conflicts - would you mind solving those?

**Comment by miniak** [comment]
I will have a look tomorrow. I have noticed some refactoring in master, which looked like it would conflict with my changes

**Comment by miniak** [comment]
I have updated the PR

**Comment by felixrieseberg** [comment]
LGTM :+1: Thanks!

**Comment by zcbenz** [comment]
:+1:

**Pull request merged**
