### PR TITLE
initialise devtools context menu onload

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/atom/electron/issues/1456

### CODE REVIEW

**Comment by deepak1556** [comment]
WIth this we dont need to override inspector api's on electron side to show up context menu. Can we remove them @zcbenz ?

**Comment by zcbenz** [comment]
The soft menu can not show outside the window, so if the menu is longer than the window's height, you have to scroll the menu to be able to use it, which is pretty bad. For docked devtools, this happens almost for every menu.

**Comment by deepak1556** [comment]
Ah yeah didnt try it on a smaller window docked, looks bad. But will users debug in such small windows ? 
So we need to get inspector api run for webview to fix that issue i guess if this is not an option.

**Comment by zcbenz** [comment]
Docked devtools is very useful when you work on HTML/CSS or only want to run a few lines of code in console, I believe most people use devtools docked.

The root cause is `remote.getCurrentWindow` doesn't work in webview's devtools, we should fix it instead of working around it.

**Comment by deepak1556** [comment]
cool :+1:

**Pull request closed without merging**
